I devide fun-def into some .h then #include but error also, the error message is: e:\vc\bigarr\m.c(35) :   fatal error C1001: INTERNAL COMPILER ERROR I think the reason is still fun-def too more.